### ISSUE TITLE
Installing content_package does not work

### ISSUE THREAD

**Issue by rodehoed** [OpenSCAP/puppet-openscap#1]
It seems the content_package is not being installed before the scan is being executed and thus gives an error.  When I do install scap-security-guide-0.1.5-4.el7.noarch manually the puppet class runs without errors/problems.
# Steps to reproduce:

1) be sure scap-security-guide is not installed: rpm -e scap-security-guide
2) Use the following class in Puppet:
class { openscap::xccdf::eval:
      name                    => 'PRIVATE-weekly-OpenSCAP-audit',
      content_package  => ['scap-security-guide'],
      weekday               => Friday,
      period                   => weekly,
  }
3) Run puppet. It spits out the error below
# Expected result:

The content_package should be pulled in before the xccdf_scan is being executed.
# Environment:

RHEL 7
scap-security-guide-0.1.5-4.el7.noarch
Puppet v3.4
isimluk-openscap 0.3.1
# Error:

Error: Could not set 'present' on ensure: undefined method `destroy' for nil:NilClass at 64:/etc/puppet/modules/openscap/manifests/xccdf/eval.pp
Error: Could not set 'present' on ensure: undefined method`destroy' for nil:NilClass at 64:/etc/puppet/modules/openscap/manifests/xccdf/eval.pp
Wrapped exception:
undefined method `destroy' for nil:NilClass
Error: /Stage[main]/Openscap::Xccdf::Eval/Xccdf_scan[untitled]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method`destroy' for nil:NilClass at 64:/etc/puppet/modules/openscap/manifests/xccdf/eval.pp

**Comment by yuumasato** [comment]
Closing this as project is deprecated.
